### PR TITLE
Add cursor type for more safety.

### PR DESCRIPTION
**Pull request by nickmshelley**

### CODE REVIEW

**Comment by nickmshelley** [comment]
This gives a much better diff (adding `?w=1` to the URL): https://github.com/stephencelis/SQLite.swift/pull/647/files?w=1

**Comment by nickmshelley** [comment]
Most of the discussion around this PR happened in #569.

**Comment by stephanheilner** [comment]
👍

**Comment by stephanheilner** [comment]
What is the status of this PR? I'd love to have this crash fix in my apps. @jberkel @stephencelis

**Comment by nickmshelley** [comment]
Is there anything else that should be done to get this merged @jberkel? If it's just that you don't have time to look into it more, I can just go ahead and merge it.

**Comment by jberkel** [comment]
@nickmshelley can you rebase this PR against the release branch?

**Comment by nickmshelley** [comment]
@jberkel I opened #726 against the release branch.

Thanks for taking the time to update the library and deal with PRs and issues.

**Comment by jberkel** [comment]
replaced w/ #726

**Pull request closed without merging**
