### PR TITLE
Add connection pool for concurrent access

### PR DESCRIPTION
**Pull request by kdubb**
Implements a multi-reader, single-writer connection pool using SQLite's WAL mode.

Would love feedback on the implementation and any suggested changes to the implementation.

### CODE REVIEW

**Comment by stephencelis** [comment]
Thanks for the PR! This is really awesome! I'll have to look over this soon when I get back into town and settled.

**Comment by ryanholden8** [comment]
Would love to see this added! Any update on status of merge? @stephencelis Thank you!

**Comment by kdubb** [comment]
I have many chances to this that have yet to be pushed to my repo.  As we began a rewrite of our database code we found a few problems.  I will try to get them ready for commit very soon.

**Comment by stephencelis** [comment]
@kdubb Look forward to it!

**Pull request closed without merging**
