### PR TITLE
Numeric type workaround

### PR DESCRIPTION
**Pull request by semka**
Hi there. 

We are facing #331 problem really hard. One of our apps using remote database and we can't actually change it's schema to fix types.

I know this code is ugly as hell, but it works and even has unit test-coverage :)
I will be happy if someone fix this issue in proper way, but for now we desperately need workaround.

### CODE REVIEW

**Comment by semka** [comment]
Hey, guys. 17 days passed and still no reaction. That's make me and my projects sad. We forced to switch on my fork which considered bad thing to do.

**Comment by stephencelis** [comment]
@semka Have you tried using `cast`?

``` swift
let doubleColumn = cast(column) as Expression<Double>
```

**Comment by semka** [comment]
Will check, thanks a lot, stephen.

**Comment by jberkel** [comment]
No activity, closing.

**Pull request closed without merging**
