### PR TITLE
fix create/drop index functions

### PR DESCRIPTION
**Pull request by kireev165**
According to documentation I can do this:
```swift
try db.run(users.createIndex(email, ifNotExists: true))
// CREATE INDEX IF NOT EXISTS "index_users_on_email" ON "users" ("email")
```
and this:
```swift
try db.run(users.createIndex(email, ifNotExists: true))
// CREATE INDEX IF NOT EXISTS "index_users_on_email" ON "users" ("email")
```
But in fact:
```swift
import SQLite

let table = Table("table")
let field = Expression<Int64>("field")
table.createIndex(field, unique: true, ifNotExists: true)
// error: cannot convert value of type 'Expression<Int64>' to expected argument type '[Expressible]'
// table.createIndex(field, unique: true, ifNotExists: true)
table.dropIndex(field, ifExists: true)
// error: MyPlayground.playground:6:17: error: cannot convert value of type 'Expression<Int64>' to expected argument type '[Expressible]'
// table.dropIndex(field, ifExists: true)
```

So I removed:
```swift
public func createIndex(_ columns: Expressible...) -> String
public func dropIndex(_ columns: Expressible...) -> String
```
and changed:
```swift
public func createIndex(_ columns: [Expressible], unique: Bool = false, ifNotExists: Bool = false) -> String
public func dropIndex(_ columns: [Expressible], ifExists: Bool = false) -> String
```
to:
```swift
public func dropIndex(_ columns: Expressible..., ifExists: Bool = false) -> String
public func dropIndex(_ columns: Expressible..., ifExists: Bool = false) -> String
```

### CODE REVIEW

**Comment by kireev165** [comment]
iOS version was updated to solve build error:
> xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:10.3, name:iPhone 6s }
	The requested device could not be found because no available devices matched the request.

But now there is a new problem that I don't really understand.
So, anyone, please look at travis logs.

**Comment by jberkel** [comment]
@kireev165 if you rebase against master it should work

**Comment by kireev165** [comment]
@jberkel thanks. it seems that everything fine now

**Comment by jberkel** [comment]
applied: ac52569861e6ced88f168be1fca2e20bcd1118cd

**Pull request closed without merging**
