### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by kdubb**
Retreats from the use of `fatalError` to report most errors and takes up the Swift error handling mechanism.  Found being able to throw errors extremely useful when writing custom binding code (e.g. external implementations of Value).

Not sure this PR is complete yet. Wanted to give an early look to see your thoughts.  It piggybacks on my connection_pool branch/PR at the moment.

### CODE REVIEW

**Comment by nickmshelley** [comment]
This would be awesome to have, but it seems to depend on https://github.com/stephencelis/SQLite.swift/pull/411 at the moment. Would it be better to make it a standalone PR or just wait until https://github.com/stephencelis/SQLite.swift/pull/411 is finished up and merged?

**Comment by maun** [comment]
What is the state of this PR? I am hitting the issue in #430 and cant use the library because of this. Can I help somehow?

**Comment by brandenr** [comment]
#411 has merged. Is this one ready to be finished?

**Comment by nickmshelley** [comment]
#398 and #470 were merged, but a new release hasn't been created since then. Those were the only functions I cared used that could crash, so I probably won't do anything with this one since it goes a lot deeper than I care to.

**Comment by jberkel** [comment]
#736

**Pull request closed without merging**
