### PR TITLE
Resolve Podspec version to semantic version

### PR DESCRIPTION
**Pull request by hiltonc**

### CODE REVIEW

**Comment by stephencelis** [comment]
Is this preventing installation/use for you?

**Comment by hiltonc** [comment]
It installs fine, but I can't submit the resulting app because one of the iTC verification checks is to see that all frameworks have an x.y.z (all integers) version. I patterned this after the corresponding commit on master, happy to make whatever changes you need.

**Comment by stephencelis** [comment]
Hm, I thought that iTC requirement was made more lenient. I wonder if we can make this 0.9.9 till 1.0.0 is finalized?

**Comment by hiltonc** [comment]
I got this today:

    [08:51:23]: [Transporter Error Output]: ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '1.0.0.pre' in the Info.plist file must be a period-separated list of at most three non-negative integers."

I'll change it to 0.9.9

**Comment by hiltonc** [comment]
This PR is now updated with "0.9.9"

**Comment by stephencelis** [comment]
Sorry about the confusion. The `swift-2` branch should have been deleted. I've rectified the situation. Please use the `master` branch! And thanks for the PR!

**Comment by hiltonc** [comment]
Ah, cool. Thank you!

**Pull request closed without merging**
