### PR TITLE
Making small change so that this can play nice with SQLiteCipher.swift

### PR DESCRIPTION
**Pull request by gblotter**
Needed to make `func check()` be public, so that SQLiteCipher.swift can access it in it's extension of the Connection class.

Please let me know what questions you have.  if there is a better way of doing this, I'm open to suggestions.  If you want to check out the details of the PR I have coming for the SQLiteCipher.swift repository, that uses this change, you can check it out here: https://github.com/gblotter/SQLite.swift/tree/SQLiteCipher-play-nice

### CODE REVIEW

**Comment by gblotter** [comment]
@stephencelis Any chance you've had a second to check out this PR?  😊

**Comment by stephencelis** [comment]
Not yet, sorry! Will try to find some time later today.

**Comment by stephencelis** [comment]
@gblotter Do you have a link to your use in SQLiteCipher?

**Comment by gblotter** [comment]
@stephencelis yeah, there is a a PR waiting for you in the repo w/ my use.

**Comment by pepejeria** [comment]
Any chance of having this minor PR reviewed? Would be great to have SQLiteCipher sorted out. Thanks

**Comment by TheNephilim88** [comment]
+1

**Comment by multiholle** [comment]
bump

**Comment by jberkel** [comment]
This is now part of #531

**Pull request closed without merging**
