### PR TITLE
Move OSX deployment target back to 10.10

### PR DESCRIPTION
**Pull request by jberkel**
See #1094

### CODE REVIEW

**Comment by calvincestari** [comment]
Hi @jberkel, do you know when the next release might go out?

**Comment by jberkel** [comment]
@calvincestari I'll see if I can get it out soon, there's nothing really waiting for it

**Comment by jberkel** [comment]
@calvincestari 0.13.1 is out now!

**Comment by calvincestari** [comment]
Thank you @jberkel!

**Pull request merged**
