### PR TITLE
Xcode8

### PR DESCRIPTION
**Pull request by jberkel**

### CODE REVIEW

**Comment by stephencelis** [comment]
Given GM release, do you suppose Travis is up to the task yet?

**Comment by jberkel** [comment]
hope so, i'll give it a go

**Comment by stephencelis** [comment]
Thanks so much for your regular contributions, @jberkel! Always great stuff.

**Comment by jberkel** [comment]
glad to be able to help. the pod integration tests run fine locally now but stall on travis. not quite sure what's going on, investigating...

**Comment by jberkel** [comment]
Would be great if somebody could sanity check these changes. The tests now run on Xcode 7 and 8. However there are currently intermittent failures on Xcode 8, this is a known problem, see https://github.com/travis-ci/travis-ci/issues/6422 for a discussion.

Let's hope that things will get more stable with coming updates.

**Comment by mbarclay** [comment]
Hi @jberkel. The xcode8 branch is working well for me using Carthage, Xcode 8, Swift 2.8. Are you aware of the `sqlite3_trace` deprecation warning? Superseded by `sqlite3_trace_v2`.

**Comment by jberkel** [comment]
@mbarclay i've noticed the warning, no need to worry. SQLite development is quite conservative and probably won't break compatibility in another 50 years :).  would still be good to address this, maybe in separate PR though.

**Comment by jberkel** [comment]
@mbarclay FYI #517

**Comment by jberkel** [comment]
closing in favor of #502

**Pull request closed without merging**
