### PR TITLE
Created a subspec in your podspec file for SQLiteCipher

### PR DESCRIPTION
**Pull request by gblotter**
The reason why I took this approach is one had to compile the SQLite.swift library to use a codec if they were to get the goodness of SQLCipher, yet the only difference between your other repo and this one was the presence of the Cipher.swift file.

This approach does NOT add the Cipher.swift file to the Xcode project, but rather includes it in the pod's subspec so that if someone chooses to install it, it is present in the build SQLite.swift framework.

If this PR is accepted and merged, than #389 wouldn't be necessary, and neither would the separate git repo for SQLiteCipher.swift (especially https://github.com/stephencelis/SQLiteCipher.swift/pull/12)

### CODE REVIEW

**Comment by pepejeria** [comment]
Any update on this?

**Comment by TheNephilim88** [comment]
@stephencelis ?

**Comment by jberkel** [comment]
This needs rebasing since there are now sub specs defined in the current master.

Also not sure if `SWIFT_INCLUDE_PATHS` is needed in the subspec. Otherwise there'll be a mixup of `CSQLite` (defined by the system) and the `SQLiteCipher` framework. 

I'm not sure how SQLiteCipher would integrate, presumably we'd need another compile time flag?

```swift
#if SQLITE_SWIFT_STANDALONE
import sqlite3
#else if  SQLITE_SWIFT_SQLITECIPHER
import SQLiteCipher
#else
import CSQLite
#endif
```

**Comment by jberkel** [comment]
No activity, closing. Please reopen a new PR if needed.

**Comment by jberkel** [comment]
this has been reworked into #553

**Pull request closed without merging**
