### PR TITLE
[CocoaPods] Add SQLite module map for each architecture

### PR DESCRIPTION
**Pull request by cjwirth**
Piggy-backing off of https://github.com/stephencelis/SQLite.swift/pull/380

## ☝️ What does this PR do?

This fixes the build problem where people were unable to build depending on what version of Xcode they were using. I know, it sounds bizarre...

## ✌️ How does it do it? 

I split up the module maps up by architecture, and imported them in the private build settings (basically the same technique I mentioned in [this comment](https://github.com/stephencelis/SQLite.swift/issues/349#issuecomment-199859137))

## 📖  More Information!

While I was investigating, I downloaded both versions of Xcode (dmg and AppStore). The dmg version was fine. The AppStore version would build for devices, but not for the simulator. But! If I rearranged the order of the `x86`, `arm`, `arm64` modules, I could get it to succeed/fail in building in the other way around!

So I thought, I don't know which version of Xcode is correct, but one of them is certainly buggy. But it would be better if it would build for anyone regardless of what version of Xcode they were using.

Yeah, it's a little disappointing to have more files like this to take care of, but I couldn't find another way to make a kind of 'conditional import'. 

Plus! I've gotten it to successfully build on CircleCI, so that make me feel a little bit better! :smile:

### CODE REVIEW

**Comment by acrookston** [comment]
This was the first time my build went through on the build server (trying out BuddyBuild). The previous solution only worked locally.

**Comment by stephencelis** [comment]
Round and round we go :)

This is similar to one of the first solutions I had to this problem. The way SwiftPM works makes it a more ideal candidate, too, so :+1:.

**Comment by stephencelis** [comment]
Thanks for investigating! This Xcode update was rockier than I think we all hoped :smile:

**Comment by cjwirth** [comment]
Thanks :smile: 

Yeah I hadn't really followed all the changes as they started happening. I got sick the day after this all started, and just got better in time to pick up the rear end! 

> This Xcode update was rockier than I think we all hoped 

Yeah, no kidding... In more ways than just this library too!

:+1:

**Comment by fuxx** [comment]
Hey :)
Looks good to me, but i am still wondered why this works without the umbrella header.

I try to apply the solution to my own project, but my project requires the umbrella header in the module map.

**Comment by stephencelis** [comment]
@fuxx I believe it's because this module map exists in addition to the generated one, with a _different_ module name (`CSQLite` in this case).

**Pull request merged**
