### PR TITLE
Add test for single connection across multiple threads.

### PR DESCRIPTION
**Pull request by nickmshelley**

### CODE REVIEW

**Comment by nickmshelley** [comment]
This should fail tests until https://github.com/stephencelis/SQLite.swift/pull/472 is through, which is what broke this functionality.

**Comment by nickmshelley** [comment]
Hm... this fails locally every time...

**Comment by nickmshelley** [comment]
Travis is having issues at the moment. I'll try to see if I can get this to fail on Travis when it's happy again.

I'm worried that the tests run on a single-core machine/VM, so it might be hard to get it to fail consistently on Travis, whereas locally it fails immediately for me.

**Comment by jberkel** [comment]
Merged into release

**Pull request closed without merging**
