### PR TITLE
Use hard-coded SDK path for system module map

### LINKED ISSUE #319: carthage build failed
The carthage build failed on my mac. I'm using carthage 0.10.0, xcode 7.2. Following is the error message:
The following build commands failed:
	CompileSwift normal x86_64 /Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Typed/CoreFunctions.swift
	CompileSwift normal x86_64 /Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Extensions/R*Tree.swift
	CompileSwift normal x86_64 /Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Core/Blob.swift
	CompileSwift normal x86_64 /Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Foundation.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)
/Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite3/module.modulemap:2:12: error: header '/usr/include/sqlite3.h' not found
/Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Core/Blob.swift:25:8: error: could not build Objective-C module 'SQLite3'
/Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite3/module.modulemap:2:12: error: header '/usr/include/sqlite3.h' not found
/Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Core/Blob.swift:25:8: error: could not build Objective-C module 'SQLite3'
/Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite3/module.modulemap:2:12: error: header '/usr/include/sqlite3.h' not found
/Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Core/Blob.swift:25:8: error: could not build Objective-C module 'SQLite3'
/Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite3/module.modulemap:2:12: error: header '/usr/include/sqlite3.h' not found
/Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Core/Blob.swift:25:8: error: could not build Objective-C module 'SQLite3'
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Typed/CoreFunctions.swift
	CompileSwift normal x86_64 /Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Extensions/R*Tree.swift
	CompileSwift normal x86_64 /Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Core/Blob.swift
	CompileSwift normal x86_64 /Users/ftit/Documents/lincoln/try5/Carthage/Checkouts/SQLite.swift/SQLite/Foundation.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)

### PR DESCRIPTION
**Pull request by stephencelis**
We've been down this path before. Unfortunately, `/usr/include/sqlite3.h` isn't reliably available on all Macs. Because module maps don't yet have dynamic support (something that the Swift Package Manager intends to have solved soon), we need to hardcode the SDK path (or use a script to substitute it).

Fixes #319.

@mikemee Thoughts?

### CODE REVIEW

**Comment by mikemee** [comment]
Let's  try it. I don't know if everyone has this installed either, but likely a better bet as we know now that the other is not universal.

**Comment by stephencelis** [comment]
@mikemee Yeah, I think we can make standard Xcode installation a requirement (in lieu of a better way for the moment).

**Comment by mikemee** [comment]
Don't forget to tag to 0.9.1 to keep carthage happy. Not sure if cocopods updates automagically or not. Probably should add that to the makefile later if not.

**Comment by stephencelis** [comment]
CocoaPods depends on the branch, too, so we'll be good to go :)

**Comment by mikemee** [comment]
Very nicely done!  

You also removed my CocoaPods hackery by adding the missing (_oops!_) `APPLICATION_EXTENSION_API_ONLY` and setting `fts3_tokenizer.h` private (as you'd previously suggested but I misunderstood by trying it in the Xcode file not the pod file). That all seems to have allowed CocoaPods to do it's thing correctly (_I take back all those things I said about it_ 😎), which nicely gets everything back into alignment and also removes the warning (I'm guessing).

**Comment by stephencelis** [comment]
@mikemee The warning actually went away when I removed the SQLite.swift `module.modulemap` file. I'm not sure what's different with the module map Xcode generates, but it seems to have killed that warning! :)

As far as the private header goes, I just wanted to make sure it wasn't exposed externally to CocoaPods consumers.

**Comment by mikemee** [comment]
Some combination of the two I suspect.  I didn't have the `module.modulemap` file originally and only added it when I couldn't make CocoaPods happy. However, in hindsight, CocoaPods probably wasn't happy because the `..API_ONLY` wasn't set (though I'm surprised Xcode wasn't upset without that).

Anyhow, the great thing is that it is all much improved now!

**Comment by iNoles** [comment]
What is a big deal about APPLICATION_EXTENSION_API_ONLY? By reading to https://developer.apple.com/app-extensions/, I am curious why Database needs to access it.

**Comment by stephencelis** [comment]
@iNoles I enabled it so that SQLite.swift can be used in Today/Watch/etc. extensions.

**Comment by mikemee** [comment]
Hmm, now that you've given me that link @iNoles, I realize I was confusing it with the other magic Xcode setting that says "This is a framework, not an app". (_Which I've just gone looking for but haven't found yet..._)  Sorry about the confusion.

**Pull request merged**
