### PR TITLE
Adding Date support on Codable

### PR DESCRIPTION
**Pull request by KyleLeneau**
I thought that it was pretty easy to add `Date` support to Codable so I went ahead and did that. You already had the foundation stuff so I went that route instead of setting a strategy on the JSONEncoder and Decoder to iso8601 (this wasn't going to work on anything less that iOS 10 though and looks like you support back to 8).

Please let me know if I am missing anything or you want me to change anything. I am happy to help. Thanks!

### CODE REVIEW

**Comment by kristoff-it** [comment]
Hello I think this PR should be merged ASAP, the Codable functionality is pretty crippled without this, which is also confusing considering the normal way of building queries has support for Date.

Great library and great PR, thank you all.

**Comment by KyleLeneau** [comment]
Oh shoot, I thought I added tests to this one. My mistake.

**Comment by jberkel** [comment]
@KyleLeneau thanks! there are actually tests for the existing codable functionality, in `QueryTests.swift` (look for `TestCodable`)

**Comment by kroussevrb** [comment]
The Codable functionality is useless for anything but simple example apps. Adding `Date` won't help either, because there is lack of support for other extremely popular classes.

**Comment by tulioccalazans** [comment]
Hi, when this pull request will be merged?

**Comment by mobiletoly** [comment]
I lost a hope to be honest. Many basic types were added with PR (Date, Int64 and other essential types), but nobody cares.

**Comment by groue** [comment]
Hi @mobiletoly, have a look at [GRDB](https://github.com/groue/GRDB.swift), one day. It has first-class support for [Codable](https://github.com/groue/GRDB.swift/blob/master/README.md#codable-records), and is very focused on application developer productivity: this kind of issue generally does not exist, or doesn't stay unresolved for long.

**Comment by mobiletoly** [comment]
thank you @groue 
when I was evaluating GRDB few months ago I think that I had an issues with compiling for Swift 5. but seems like they claim a support for Swift 5. will give it a try again!

**Pull request closed without merging**
