### PR TITLE
propagate errors in Statement initialization

### PR DESCRIPTION
**Pull request by kujenga**
Propagates up errors by replacing a `try!` in the init method for Statements with try and adding the necessary acknowledgements of this throughout the code.

see: https://github.com/stephencelis/SQLite.swift/issues/220

### CODE REVIEW

**Comment by stephencelis** [comment]
Gah, GitHub automatically closes PRs that are trying to merge against deleted branches (swift-2 was merged in).

**Comment by kujenga** [comment]
Ah, no worries! Is there anything your still looking for on this?

**Comment by kujenga** [comment]
@stephencelis Any updates on your thoughts on this PR? Just let me know if there's anything else you'd like to see.

**Comment by kujenga** [comment]
@stephencelis Was this intentionally closed or was it another automatic one?

**Comment by stephencelis** [comment]
Sigh. This is a result of GitHub closing PRs automatically that target branches that get deleted. Any chance you can re-open this against master?

**Comment by kujenga** [comment]
Will do!

**Pull request closed without merging**
