### PR TITLE
Allow the framework to be included in app extensions for tvOS

### PR DESCRIPTION
**Pull request by Tableau-David-Potter**

### CODE REVIEW

**Comment by Tableau-David-Potter** [comment]
Is there a plan to accept this merge request?

**Comment by jberkel** [comment]
Not sure how app extensions are supposed to work, but isn't this a setting which is very use case specific? How do you integrate SQLite.swift in your project? Maybe you could override it in your project settings?

**Comment by Tableau-David-Potter** [comment]
@jberkel This setting is required on all frameworks that are included in an extension app, such as a Today widget extension or a watch extension.

**Comment by jberkel** [comment]
Well that was point – the users who actually need to set it can probably do so in their own project?

**Comment by Tableau-David-Potter** [comment]
@jberkel Please try including this framework into a tvOS project and tell me what you see.  When I do this I get a warning telling me that I'm "linking against a dylib which is not safe for use in application extensions."  You can see my report in issue #445.

**Comment by jberkel** [comment]
How do you integrate the framework in your project?

**Comment by Tableau-David-Potter** [comment]
Using Carthage.

**Comment by jberkel** [comment]
Ah ok, in which case you can't easily change the config. Also this setting already exists in the other targets so we should apply it consistently. Can you update the branch so it can get merged?

**Pull request merged**
