### PR TITLE
Swift 2

### PR DESCRIPTION
**Pull request by stephencelis**
This is a work in progress with much to do. It's an ambitious update that adds support for Swift 2 features along with some project file restructuring needed to support Carthage, and API restructuring needed to decouple database connections from the query builder and support database names.

It will address #133, #30, #77.

Old code has momentarily been deleted and functionality with it. This PR will not work with your existing code at the moment. See **Tests** and read the **Source** for new behavior.

Must-haves:

- [x] Use Swift 2 error model
- [x] Use protocol extensions
- [x] Feature parity
    - [x] Re-hook up `asc`, `desc`, `alias`
- [x] Re-hook up SQLCipher
- [x] Re-hook up CocoaPods
- [ ] Finish tests (and provide as complete coverage as possible)
- [ ] Update documentation
    - [x] Update general text and example code
    - [ ] Address FIXMEs
    - [ ] Update installation instructions and image
    - [ ] Add more specific examples around expression protocol extensions
- [ ] Update playground
- [x] Update README (partially done)
    - [x] Update general text and example code
    - [x] Update installation instructions and image

Nice-to-haves:

- [x] Decouple database connections from query builder
- [x] Hook up Carthage
- [x] Database name support
- [ ] Attach/detach helpers
- [ ] Pragma helpers
- [ ] Extract SQLCipher into its own SQLiteCipher.swift repository
- [ ] Section playground into chapters with more examples
- [ ] Clean up raw interface
    - [ ] Consider less subscripting and more flexibility for retrieving values
    - [ ] Use `func forEach(Element -> Void) throws` for lazy iteration
- [ ] Split into sub-frameworks (don't require typed builder use)
- [ ] Multi-reader/single-writer locking

### CODE REVIEW

**Comment by schickling** [comment]
Good job! :+1:

**Comment by schickling** [comment]
Any news about when `.order` by `.asc`/`.desc` can be expected?

**Comment by Silve2611** [comment]
I have tried to include this WIP into a simple Project that onle wirtes a console line on a click. I cannot compile the project as it shows errors imidiately. 

Should this work be know or should I keep my hands of the WIP and wait for a master version. I wanted to prepare myself for swift 2.0

**Comment by stephencelis** [comment]
@Silve2611 It should work, for the most part, but errors aren't surfaced in the most helpful way yet. Can you paste the code/errors failing in question?

**Comment by Silve2611** [comment]
bildschirmfoto 2015-08-22 um 22 52 04
I added a screenshot. But I have to admit the behaviour is Strange. Now when I build it. It fails but shows no errors. Removen SQLite from the project solves this...

**Comment by Silve2611** [comment]
Ok now with the Beta 5 Version I can compile the code but only if I do not import SQLite. 
As soons as I `import SQLite` and try `let db = Database("")` I'm getting an error `use of unresolved identifier 'database'`

Is there something I am not doing right?

**Comment by Silve2611** [comment]
Since i have made the update everything is working fine. Thank you for the great work!

**Comment by lukescott** [comment]
May be a good idea to tag a release for the current Swift 1.2 version. That way when the Swift 2.0 version comes out you can do a major version bump and those who haven't made the transition can select the Swift 1.2 version until they've updated their code.

**Comment by cwack-letsdev** [comment]
Hi I migrated to your swift 2.0 branch. How I have to migrate following coe to your optimised API?

magazines.filter(contains(favoritMagazines, DbMagazine.COLUMN_ID))  ?

thx

**Comment by stephencelis** [comment]
@cwack-letsdev Protocol extensions have made the following possible (and preferable):

```
magazines.filter(favoriteMagazines.contains(DbMagazine.COLUMN_ID))
```

**Comment by stephencelis** [comment]
Merging! A few things to do but things should be relatively stable.

**Pull request merged**
