### PR TITLE
Fix swift package build

### LINKED ISSUE #1058: Move to GitHub Actions (instead of travis-ci.org)
The old travis.org service is [no longer available](https://blog.travis-ci.com/2021-05-07-orgshutdown).
You need to activate something in order to move the CI to travis-ci.com. PRs won't be able to get merged otherwise

### PR DESCRIPTION
**Pull request by jberkel**
Fixes #1058

### CODE REVIEW

**Comment by NathanFallet** [comment]
Waiting for checks to complete before merging it (hope it will work)

**Comment by jberkel** [comment]
hmm, maybe we should disable the pods tests on regular builds, they take forever. they could be run before releasing.

**Comment by NathanFallet** [comment]
Let's keep them as it for now. At least we'll be sure everything works. And when a PR is opened, we don't see it directly so it has enough time to build everything.

**Comment by NathanFallet** [comment]
@jberkel Now we have to publish a new release (for xcode support and fixes mainly).
Also, DM me on Twitter [@NathanFallet](https://twitter.com/NathanFallet) so that we can talk about everything easily.

**Comment by jberkel** [comment]
@NathanFallet don't have twitter, I'll send you an email

**Pull request merged**
