### PR TITLE
Add note about enabling modules in Xcode project

### PR DESCRIPTION
**Pull request by skagedal**
Closes issue #925 – not an SQLite.swift issue, but an SwiftPM one, but worthy of a note here imo.

### CODE REVIEW

**Comment by danramteke** [comment]
I would prefer that we make the change that Ankit recommends here https://bugs.swift.org/browse/SR-8629

**Comment by skagedal** [comment]
@danramteke Excellent, that is of course a much better solution if possible.

**Comment by ypopovych** [comment]
@danramteke can you provide PR for this fix?

**Comment by skagedal** [comment]
@ypopovych [Here is a PR](https://github.com/stephencelis/SQLite.swift/pull/933) – just an updated version of what @danramteke provided [here](https://github.com/stephencelis/SQLite.swift/pull/885)

**Comment by skagedal** [comment]
Confirmed that it works by just doing what I did [here](https://github.com/stephencelis/SQLite.swift/issues/925#issue-442836186) but instead pointing SwiftPM to my branch.

**Comment by ypopovych** [comment]
merged PR

**Pull request closed without merging**
