### PR TITLE
Change deployment targets for Xcode 15 and add dependency on custom Cocoapods fork

### PR DESCRIPTION
**Pull request by SagarSDagdu**
This PR demonstrates how to fix the issue of not being able to push podspec to Cocoapods from Xcode 15 due to minimum deployment target issues.
Check this comment for more information: https://github.com/stephencelis/SQLite.swift/issues/1250#issuecomment-2053121732

### CODE REVIEW

**Comment by nathanfallet** [comment]
Is 11 not the minimum one? Why skipping it to use 12 instead?

**Comment by SagarSDagdu** [comment]
@nathanfallet iOS 12 is the minimum deployment target for Xcode 15.
Ref:  https://developer.apple.com/support/xcode/
Screenshot 2024-04-13 at 5 40 04 PM

**Comment by nathanfallet** [comment]
Yeah sorry I noticed it after asking. Also, it's marked as WIP, can this be merged? At least I'm trying to publish the update based on your branch, it's building...

**Review by nathanfallet — APPROVED** [review]

**Comment by SagarSDagdu** [comment]
Hey @nathanfallet,this can be merged

**Comment by nathanfallet** [comment]
@SagarSDagdu Thank you for your time helping to solve this issue!
Also note that when cocoapods will officially update to support this we will go back to the original track (so just remove `Gemfile` + `Gemfile.lock`)

**Comment by SagarSDagdu** [comment]
Hey @nathanfallet, it is a pleasure contributing to this repo.
Yes, we can go back to the original track once Cocoapods fixes this, I will keep track of this and create a PR in the future.

**Comment by nathanfallet** [comment]
Also note that this one will have to be reverted at the same time (otherwise it won't work I guess)
https://github.com/stephencelis/SQLite.swift/pull/1237/commits/59e0597d43c12c028a4db0ee885d90d0deb3c4a7

**Comment by SagarSDagdu** [comment]
@nathanfallet Noted!

**Pull request merged**
