### PR TITLE
Made public the function bind(value:atIndex:) of class Statement

### PR DESCRIPTION
**Pull request by aaresu**
I have made public the function to use it when I want to research better performance for working with large dataset.

### CODE REVIEW

**Comment by jberkel** [comment]
Why is this needed?

**Review by NathanFallet — APPROVED** [review]
Need to check if new CI tests are passing, but looks great!

**Comment by jberkel** [comment]
As I said before, I'm not sure what this is trying to solve. There's also a pointless addition of a file already present in the repo (possibly due to merge).

**Comment by NathanFallet** [comment]
So this should not be merged?

**Comment by jberkel** [comment]
No, let's close this.

**Pull request closed without merging**
