### PR TITLE
0.11.1

### PR DESCRIPTION
**Pull request by jberkel**
Various small fixes which should go into the next release
- [ ] Fix screenshots on cocoadocs.org
- [x] Add SQLiteMigrationManager docs
- [ ] SQLiteCipher compatibility?

### CODE REVIEW

**Comment by stephencelis** [comment]
This looks good! Any thought on directing users to [SQLiteMigrationManager](https://github.com/garriguv/SQLiteMigrationManager.swift) in the docs for more advanced migration needs?

**Comment by jberkel** [comment]
Yes, only concern is that it hasn't been updated in a while. I know the developer, maybe I'll give him a nudge.

**Comment by jberkel** [comment]
@stephencelis OK, there will be an update of the migration manager soon. once that's done I'll add it to the docs.

**Comment by stephencelis** [comment]
Ah nice! Otherwise I am totally cool with removing it if/when it's unmaintained.

**Comment by jberkel** [comment]
To fix images on CocoaDocs: https://github.com/CocoaPods/cocoadocs.org/issues/482

**Pull request merged**
