### PR TITLE
CocoaPods static libraries support

### PR DESCRIPTION
**Pull request by MrAsterisco**
I have tried to include this library as a CocoaPods dependency in a iOS application where the `use_frameworks!` option is not enabled. The reason to remove this option is mainly related to startup times, as reported by multiple sources around the web.

The issue with this library is related to how the `SQLite-Bridging.h` is linked in `SQLite.h`. When included as a static library, the aforementioned file can't be reference using `<>` but needs to be imported as a normal file.

I've made the necessary changes and I'd like to see these implemented in the main project. I'm not aware of incompatibilities with other package managers (such as Carthage).

### CODE REVIEW

**Comment by danramteke** [comment]
This change works for me.

**Comment by MrAsterisco** [comment]
@danramteke Thank you! How do we proceed? I don't have permissions to merge this pull request.

**Comment by ypopovych** [comment]
Do we have this problem with the latest one?

**Comment by danramteke** [comment]
@MrAsterisco I am not an admin on this repo.

**Comment by isnine** [comment]
This change works for me too.

**Pull request closed without merging**
