### PR TITLE
Prepare and publish 0.11.0

### PR DESCRIPTION
**Pull request by jberkel**

### CODE REVIEW

**Comment by jberkel** [comment]
Can somebody please review&merge if it looks ok? Would like to avoid merging my own PRs.

What else is required to do a new release?

**Comment by jberkel** [comment]
@stephencelis If you're ok with it I could do the upcoming  0.11.0 release, would need access to CocoaPods trunk though to publish the pod. 

It would be good to get it out soon since we don't have a published version supporting Swift3 at the moment, and a few confused users as a result (#527).

**Comment by stephencelis** [comment]
@jberkel (and everyone waiting): sorry for the delay! I was traveling and am unfortunately the only one with keys to CocoaPods right now. I'll correct that ASAP.

**Comment by jberkel** [comment]
ok, just published 0.11.0! 🍾 

will be great to finally start working on new features, feels like the last month has just been migration / maintenance work...

**Pull request merged**
