### PR TITLE
Add transaction method which takes an array of Statements as its unique parameter

### PR DESCRIPTION
**Pull request by juliensagot**

### CODE REVIEW

**Comment by stephencelis** [comment]
Do you have more information on the problem you're solving for here? Is this a matter of avoiding calling `.Deferred` explicitly?

**Comment by stephencelis** [comment]
Ah, never mind. I didn't realize that the array function was private. Should we publicize that one, too?

**Comment by juliensagot** [comment]
Yeah, that would be great ! 👍

**Comment by stephencelis** [comment]
Thanks!

**Pull request merged**
